#!/bin/sh

export XX_MODE=bashrc

if [[ -f ~/.bashrc.local ]]; then
    source ~/.bashrc.local
fi

if [[ -f ~/.env.sh ]]; then
    source ~/.env.sh
fi

export PATH=$HOME/lcoal/bin:$PATH

# added by travis gem
[ -f /Users/keisukefukuda/.travis/travis.sh ] && source /Users/keisukefukuda/.travis/travis.sh

# if [[ "$-" == *i* ]]; then
  # if [[ "$(uname)" == *Darwin* ]]; then
    # exec zsh
  # fi
# fi

# mpienv use --mpi4py openmpi-2.1.2


export PATH=/usr/local/bin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"
export PFKUBE_DOCKER_ALLOWED_RUNTIME_UID=2106
export PFKUBE_DEFAULT_DOCKER_REGISTRY=harbor.pfn.io/user-kfukuda


export PFKUBE_DOCKER_ALLOWED_RUNTIME_UID=2106
export PFKUBE_MNJ_DEFAULT_DOCKER_REGISTRY=harbor.mnj.pfn.io/user-kfukuda  # This is used when --target-cluster=mnj
export PFKUBE_MNJ_KUBECTL_CONTEXT=mnj  # This is used when --target-cluster=mnj

export PFKUBE_DOCKER_ALLOWED_RUNTIME_UID=2106
export PFKUBE_MNJ_KUBECTL_CONTEXT=mnj  # This is used when --target-cluster=mnj
export PFKUBE_MNJ_DEFAULT_DOCKER_REGISTRY=harbor.mnj.pfn.io/user-kfukuda  # This is used when --target-cluster=mnj
export PFKUBE_MNJ_DEFAULT_DOCKER_CRED_NAME=pfkube-harbor-cred  # This is used when --target-cluster=mnj
export PFKUBE_MNJ_DEFAULT_GIT_SECRET_NAME=pfkube-git-secret  # This is used when --target-cluster=mnj