#!/bin/sh

if [[ -f ~/.bashrc.local ]]; then
    source ~/.bashrc.local
fi


export PATH=$HOME/lcoal/bin:$PATH

# added by travis gem
[ -f /Users/keisukefukuda/.travis/travis.sh ] && source /Users/keisukefukuda/.travis/travis.sh

if [[ "$?" -eq "0" && ( "$-" == *i* ) ]]; then
  if [ -x /usr/local/bin/zsh ]; then
    exec zsh -l
  fi
fi
