(source gnu)
(source melpa)

(package-file "cask.el")

;; (files "*.el" "bin" "templates")

(depends-on "f")
(depends-on "s")
(depends-on "ansi")
(depends-on "ecukes")
(depends-on "servant")
(depends-on "ert-runner")
(depends-on "el-mock")
(depends-on "noflet")
(depends-on "ert-async")

(depends-on "bind-key")
(depends-on "bison-mode")
(depends-on "cask")
(depends-on "cmake-mode")
(depends-on "clang-format")
(depends-on "company")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "company-go")
(depends-on "helm")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "yasnippet")

;; Git-related
(depends-on "magit")
(depends-on "git-gutter+")

;; rust-related
(depends-on "rust-mode")
(depends-on "flymake-rust")
(depends-on "flycheck-rust")

;; Clojure-related
(depends-on "cider")
(depends-on "ac-cider")
(depends-on "clojure-mode")
(depends-on "smartparens")
; (depends-on "slamhound")
(depends-on "paredit")

;; Clojureに用途が限定されたパッケージではないが必要なもの
(depends-on "rainbow-delimiters")

;; Julia-related
(depends-on "flycheck-julia")
(depends-on "julia")
(depends-on "julia-repl")
(depends-on "julia-shell")



(depends-on "markdown-mode")

;; C++
;; http://qiita.com/MitsutakaTakeda/items/2f526a85ad39424a8363
(depends-on "irony")
(depends-on "irony-eldoc")
(depends-on "company-irony")
(depends-on "flycheck-irony")
(depends-on "rtags")

;; Haskell
(depends-on "haskell-mode")
;(depends-on "haskell-cabal")


